-- MySQL Script generated by MySQL Workbench
-- Mon Nov 28 19:39:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cep` INT(8) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profissional` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `especialidade` VARCHAR(45) NOT NULL,
  `telefone` INT(13) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`cpf`, `Endereco_idEndereco`),
  INDEX `fk_Profissional_Endereco_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_Profissional_Endereco`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `mydb`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` INT(13) NOT NULL,
  `email` VARCHAR(45) NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`cpf`, `Endereco_idEndereco`),
  INDEX `fk_Cliente_Endereco1_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `mydb`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Animal` (
  `idAnimal` INT NOT NULL AUTO_INCREMENT,
  `especie` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `Cliente_cpf` INT NOT NULL,
  `Cliente_Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`idAnimal`, `Cliente_cpf`, `Cliente_Endereco_idEndereco`),
  INDEX `fk_Animal_Cliente1_idx` (`Cliente_cpf` ASC, `Cliente_Endereco_idEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_Animal_Cliente1`
    FOREIGN KEY (`Cliente_cpf` , `Cliente_Endereco_idEndereco`)
    REFERENCES `mydb`.`Cliente` (`cpf` , `Endereco_idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ficha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ficha` (
  `idRegistro` INT NOT NULL AUTO_INCREMENT,
  `anotacoesInternas` TEXT(500) NULL,
  `observacoesEspecialista` TEXT(500) NULL,
  `receituario` TEXT(500) NULL,
  `tipoProcedimento` VARCHAR(45) NOT NULL,
  `horario` TIME NOT NULL,
  `data` DATE NOT NULL,
  `Animal_idAnimal` INT NOT NULL,
  `Animal_Cliente_cpf` INT NOT NULL,
  `Animal_Cliente_Endereco_idEndereco` INT NOT NULL,
  `Profissional_cpf` INT NOT NULL,
  `Profissional_Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`idRegistro`, `Animal_idAnimal`, `Animal_Cliente_cpf`, `Animal_Cliente_Endereco_idEndereco`, `Profissional_cpf`, `Profissional_Endereco_idEndereco`),
  INDEX `fk_Ficha_Animal1_idx` (`Animal_idAnimal` ASC, `Animal_Cliente_cpf` ASC, `Animal_Cliente_Endereco_idEndereco` ASC) VISIBLE,
  INDEX `fk_Ficha_Profissional1_idx` (`Profissional_cpf` ASC, `Profissional_Endereco_idEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_Ficha_Animal1`
    FOREIGN KEY (`Animal_idAnimal` , `Animal_Cliente_cpf` , `Animal_Cliente_Endereco_idEndereco`)
    REFERENCES `mydb`.`Animal` (`idAnimal` , `Cliente_cpf` , `Cliente_Endereco_idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ficha_Profissional1`
    FOREIGN KEY (`Profissional_cpf` , `Profissional_Endereco_idEndereco`)
    REFERENCES `mydb`.`Profissional` (`cpf` , `Endereco_idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Exame` (
  `idExame` INT NOT NULL AUTO_INCREMENT,
  `resultado` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `horario` TIME NOT NULL,
  `data` DATE NOT NULL,
  `Ficha_idRegistro` INT NOT NULL,
  `Ficha_Animal_idAnimal` INT NOT NULL,
  `Ficha_Animal_Cliente_cpf` INT NOT NULL,
  `Ficha_Animal_Cliente_Endereco_idEndereco` INT NOT NULL,
  `Profissional_cpf` INT NOT NULL,
  `Profissional_Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`idExame`, `Ficha_idRegistro`, `Ficha_Animal_idAnimal`, `Ficha_Animal_Cliente_cpf`, `Ficha_Animal_Cliente_Endereco_idEndereco`, `Profissional_cpf`, `Profissional_Endereco_idEndereco`),
  INDEX `fk_Exame_Ficha1_idx` (`Ficha_idRegistro` ASC, `Ficha_Animal_idAnimal` ASC, `Ficha_Animal_Cliente_cpf` ASC, `Ficha_Animal_Cliente_Endereco_idEndereco` ASC) VISIBLE,
  INDEX `fk_Exame_Profissional1_idx` (`Profissional_cpf` ASC, `Profissional_Endereco_idEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_Exame_Ficha1`
    FOREIGN KEY (`Ficha_idRegistro` , `Ficha_Animal_idAnimal` , `Ficha_Animal_Cliente_cpf` , `Ficha_Animal_Cliente_Endereco_idEndereco`)
    REFERENCES `mydb`.`Ficha` (`idRegistro` , `Animal_idAnimal` , `Animal_Cliente_cpf` , `Animal_Cliente_Endereco_idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exame_Profissional1`
    FOREIGN KEY (`Profissional_cpf` , `Profissional_Endereco_idEndereco`)
    REFERENCES `mydb`.`Profissional` (`cpf` , `Endereco_idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
